# Auto-generated by generate_beam_mesh.jl — do not edit by hand.
# Mesh: beam_h27_80x2x2.mphtxt   FOM = 11925

domains_list = [collect(649:968)]
boundaries_list = [[1, 2, 3, 4, 5, 6, 7, 8]]
constrained_dof = [[1, 1, 1]]
bc_vals = [[0.0, 0.0, 0.0]]

materials_list = ["polysilicon"]
density = 2.32e-3
young_modulus = 160e3
poisson_ratio = 0.22
mat = MORFE_newmaterial("polysilicon", density, young_modulus, poisson_ratio)
materials_dict = Dict("polysilicon" => mat)

info.α = 0.5369754008568333 / 500.0
info.β = 0.0
info.Φ = [1]
info.neig = 10
info.Ffreq = 1
info.Fmodes = [1]
info.Fmult = 0.5 * [5.0]
info.omega_mul = 1.0
info.style = 'c'
info.max_order = 11
info.max_orderNA = 11
dirout = compose_name_output_dir("beam_h27_80x2x2", info)
info.output_dir = dirout
