# Auto-generated by generate_beam_mesh.jl — do not edit by hand.
# Mesh: beam_h27_160x8x8.mphtxt   FOM = 276573

domains_list = [collect(5249:15488)]
boundaries_list = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]]
constrained_dof = [[1, 1, 1]]
bc_vals = [[0.0, 0.0, 0.0]]

materials_list = ["polysilicon"]
density = 2.32e-3
young_modulus = 160e3
poisson_ratio = 0.22
mat = MORFE_newmaterial("polysilicon", density, young_modulus, poisson_ratio)
materials_dict = Dict("polysilicon" => mat)

info.α = 0.5369754008568333 / 500.0
info.β = 0.0
info.Φ = [1]
info.neig = 10
info.Ffreq = 1
info.Fmodes = [1]
info.Fmult = 0.5 * [5.0]
info.omega_mul = 1.0
info.style = 'c'
info.max_order = 11
info.max_orderNA = 11
dirout = compose_name_output_dir("beam_h27_160x8x8", info)
info.output_dir = dirout
